Tracks (Development)/Tracks/Tracks/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'Tracks.views.home', name='home'),
    # url(r'^Tracks/', include('Tracks.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^Tracks/', include('TracksApp.urls', namespace='TracksApp')),
)

Tracks (Development)/Tracks/TracksApp/urls.py
from django.conf.urls import patterns, include, url
from TracksApp import views
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.tracks, name='tracks'),
    url(r'^upload',views.index, name='index'),
    url(r'^upload_MP3', views.upload_MP3, name='upload_MP3'),
    url(r'^signin', views.signIn, name='SignIn'),
    url(r'^signup', views.signUp, name='SignUp'),
    url(r'^about.html', views.about, name='About')
                       
)

Tracks (Development)/Tracks/TracksApp/models.py
from django.db import models
from django.utils import timezone
import os

# Create your models here.
class Track(models.Model):
    filename = models.CharField(max_length=50)
    filepath = models.CharField(max_length=200)

    def __unicode__(self):
        return self.filename



def handle_upload_file(f, track, path="..\\Tracks\\TracksApp\\user_mp3_files"):
    ##print(path)
    temp_dest = os.path.join(path, timezone.datetime.now().strftime('%m-%d-%Y_%H-%M-%S'))
    print(temp_dest)
    with open(temp_dest,'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

    track.filepath = temp_dest
    track.save()
    return temp_dest

Tracks (Development)/Tracks/TracksApp/views.py
# Create your views here.
from django import forms
from TracksApp_forms import *
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponseForbidden, HttpResponse
from django.core.urlresolvers import reverse
from TracksApp.models import *
import os
from django.utils import timezone
import sys
import traceback

# changed from index to upload
def index(request):
    form = UploadFileForm()
    return render(request, 'TracksApp/index.html', {'form': form})

def tracks(request):
    return render(request, 'TracksApp/tracks.html',{})

def signIn(request):
    if (request.method == 'GET'):
        return render(request, 'TracksApp/welcome.html',{})

def signUp(request):
    if (request.method == 'GET'):
        return render(request, 'TracksApp/signup.html', {})

def about(request):
    if (request.method == 'GET'):
        return render(request, 'TracksApp/about.html', {})

def upload_MP3(request):
    #print('entered uploadmp3')
    if (request.method == 'POST'):
        form = UploadFileForm(request.POST, request.FILES)
        if (form.is_valid):
            try:
                temp_mp3 = request.FILES['file']
                new_track = Track(filename=temp_mp3.name)
                handle_upload_file(temp_mp3, new_track)
                response = HttpResponse('success')
                response.status_code = 200;
                return response
            except:
                response = HttpResponse(traceback.format_exc()) # Currently sends a response with the traceback of the error. DO NOT USE IN PRODUCTION.
                response.status_code = 500;
                return response
        else:
            response = HttpResponse('form not valid')
            response.status_code = 400;
            return response
    else:
        response = HttpResponse('method not post')
        response.status_code = 400;
        return response

Tracks (Development)/Tracks/templates/TracksApp/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Tracks</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href={% static "bootstrap-3.1.1-dist/css/bootstrap.min.css" %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static "starter-template.css" %} rel="stylesheet">
    
    <!-- Universal js functions -->
    <script src={% static "sidebar.js" %} type="text/javascript"></script>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div id="navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    </div>

    <div class="container">

      <div class="starter-template">
        <h1>About Tracks</h1>
        <p class="lead">Tracks is an online music collaboration site created by UC Berkeley students in 2014. </p>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    {% load staticfiles %}
    <script src={% static "bootstrap-3.1.1-dist/js/bootstrap.min.js" %}></script>
    <script type="text/javascript">
		addNav();
	</script>
  </body>
</html>

Tracks (Development)/Tracks/templates/TracksApp/index.html
<!DOCTYPE html>
<html>
<head>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
{% load staticfiles %}
<link href={% static "bootstrap-3.1.1-dist/css/bootstrap.min.css" %} rel="stylesheet">

<!-- Custom styles for this template -->
<link href={% static "starter-template.css" %} rel="stylesheet">

<!-- Universal js functions -->
<script src={% static "sidebar.js" %} type="text/javascript"></script>
</head>
<body>
<div id="navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation"></div>
hello world
{% url 'TracksApp:upload_MP3' as upload_mp3_url %}
{{ upload_mp3_url }}
<ol id="upload_list">
<li><form action="/" method="post">
{% csrf_token %}
    {% for field in form %}
            {{ field.errors }}
            {{ field.label_tag }} {{ field }}
    {% endfor %}
    <button id="upload_button" type="button">Upload</button>
    <div id='progress_div'></div>
</form>
    </li>
    </ol>


<script type="text/javascript">
    $(document).ready(function () {

        /********************************** Functions of NISHANT KUMAR ***************************************/

        /* FUNCTIONALITY: Creates a new progress bar element. 
           INPUTS: 1) html_element: 
                      The html element to add the progress bar to. 
           OUTPUT: new_bar: 
                   The progress bar element.        */
        function add_new_progress_bar(html_element) {
            var new_bar = $("<div></div>")
                .addClass("progress_bar_container");

            html_element.children().last().after(new_bar);

            html_element.children(".progress_bar_container").append(
            $("<div></div>").addClass("progress_bar_outer"));

            html_element.children(".progress_bar_container").append(
            $("<div></div>").addClass("progress_bar_inner"));

            return new_bar;
        }


        /* FUNCTIONALITY: Creates a "track element" - i.e. an li element with text and a progress bar.
                          The "track element" represents a file which is in the process of uploading.
           INPUTS: 1) preceding_text: 
                      The text to add before the progress bar.
                   2) element_to_prepend_to:
                      The html element to prepend the "track element" to (preferably a <ul> or <ol> element).
           OUTPUT: new_bar: 
                   The progress bar element of the "track element".       */
        function add_loading_track(preceding_text, element_to_prepend_to) {
            var temp = $("<li></li>").append(
            $("<span></span>").text(preceding_text + " "));
            var new_bar = add_new_progress_bar(temp);
            element_to_prepend_to.prepend(temp);
            return new_bar;
        }


        /* FUNCTIONALITY: Sets the length of the inner filling of the progress bar to visually indicate how much progress has been made.
           INPUTS: 1) progress_bar: 
                      The progress bar to set the filling of.
                   2) percent_0_to_100:
                      The percent (range 0 to 100) of the progress bar that should be filled.
           OUTPUT: None       */
        function progress_bar_setPercent(progress_bar,
    percent_0_to_100) {
            var progress_bar_max_width = parseInt(progress_bar.children("div.progress_bar_outer").css("width"), 10);
            //alert(progress_bar_max_width);
            var progress_bar_inner_margin_offset = parseInt(progress_bar.children("div.progress_bar_inner").css("margin"));
            var progress_bar_width = percent_0_to_100 * (progress_bar_max_width / 100) - 2 * progress_bar_inner_margin_offset;
            progress_bar_width = progress_bar_width.toString() + "px";
            //alert(progress_bar_width);
            progress_bar.children("div.progress_bar_inner").css("width", progress_bar_width);

            if (percent_0_to_100 == 100) {
                progress_bar.children("div.progress_bar_inner").css("background-color", "#41DD00");
            }
        }


        /* FUNCTIONALITY: Sets the inner filling of the progress bar to red in order to visually indicate a failure.
           INPUTS: 1) progress_bar: 
                      The progress bar to set the filling of.
           OUTPUT: None       */
        function progress_bar_Failure(progress_bar) {
            progress_bar.children("div.progress_bar_inner").css("background-color", "red");
        }


        /* FUNCTIONALITY: An event handler used for the event of a file upload in progress. Updates the progress bar appropriately.
           INPUTS: 1) evt:
                      The event object.
                   2) progress_bar: 
                      The progress bar to set the filling of.
           OUTPUT: None       */
        function progressHandler(evt, progress_bar) {
            if (evt.lengthComputable) {
                var percent_done = parseInt(100.0 * evt.loaded / evt.total);
                progress_bar_setPercent(progress_bar, percent_done);
            }
        }


        /* FUNCTIONALITY: An event handler used for the event of a file upload which failed. Updates the progress bar appropriately.
           INPUTS: 1) evt:
                      The event object.
                   2) progress_bar: 
                      The progress bar to set the filling of.
           OUTPUT: None       */
        function uploadFailedHandler(evt, progress_bar) {
            progress_bar_Failure(progress_bar);
        }


        /* FUNCTIONALITY: Handles uploading a file to the server asynchronously. 
                          This includes: 
                          - sending data to the server (and waiting for the response).
                          - updating the UI to reflect the progress of the file upload.
           INPUTS: None
           OUTPUT: None       */
        $('#upload_button').click(function () {
            // gets the file from the file input and prepares it for uploading
            var form_data = new FormData();
            var file_input = $('#id_file')[0];
            var file = file_input.files[0];
            form_data.append('file', file);

            // updates the UI to reflect a file which is uploading
            var new_bar = add_loading_track(file.name, $('#upload_list'));

            // updates the UI to allow the user to upload another file while the previous file is uploading
            $('#id_file').parents("form").get(0).reset();

            // the ajax request to the server to upload the file
            $.ajax({
                url: "{{ upload_mp3_url }}",
                type: 'POST',
                data: form_data,
                cache: false,        // tell the browser not to use its cache
                processData: false,  // we already have a FormData obj, so $ needs to leave it alone
                contentType: false,  // $ needs to leave the contentType alone
                xhr: function () {
                    var xhr = jQuery.ajaxSettings.xhr();
                    if (xhr.upload) {
                        xhr.upload.addEventListener('progress', function (evt) { progressHandler(evt, new_bar) }, false);
                        xhr.upload.addEventListener("error", function (evt) { uploadFailedHandler(evt, new_bar) }, false);
                    }//if
                    return xhr;
                },
                success: function (data, textStatus, jqXHR) {
                    //alert(jqXHR.responseText);
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    progress_bar_Failure(new_bar);
                    //alert(jqXHR.responseText);
                },
                async: true

            });
        });






  /********************** The following methods are not mine, they are from Django. *****************************
  ******* They allow safe POSTing with Jquery/AJAX (e.g. proper CSRF token, proper origin of request, etc.) *******/
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        function sameOrigin(url) {
            // test that a given url is a same-origin URL
            // url could be relative or scheme relative or absolute
            var host = document.location.host; // host + port
            var protocol = document.location.protocol;
            var sr_origin = '//' + host;
            var origin = protocol + sr_origin;
            // Allow absolute or scheme relative URLs to same origin
            return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
                (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
                // or any other URL that isn't scheme relative or absolute i.e relative.
                !(/^(\/\/|http:|https:).*/.test(url));
        }

        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
                    // Send the token to same-origin, relative URLs only.
                    // Send the token only if the method warrants CSRF protection
                    // Using the CSRFToken value acquired earlier
                    var csrftoken = $('input[name=csrfmiddlewaretoken]').val();
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });

    });
</script>
{% load staticfiles %}
<script src={% static "bootstrap-3.1.1-dist/js/bootstrap.min.js" %}></script>
    
<script type="text/javascript">
	addNav();
</script>
<style>
div.progress_bar_container, div.progress_bar_outer, div.progress_bar_inner {
    display: inline-block;
    position:relative;
    left:0px;
    top:-1px;
    height:10px;
}
div.progress_bar_outer, div.progress_bar_inner {
    border:1px solid black;
    position:absolute;
    padding: 0px;
    margin:0px;
}
div.progress_bar_outer {
    width:50px;
    background-color:#FFFFFF;
    z-index:-1;
}
div.progress_bar_inner {
    width:0px;
    border-color: #FFFFFF;
    background-color:#1F45FC;
    height:6px;
    margin:2px;
}
li {
    position:relative;
}
</style>
</body>
</html>

Tracks (Development)/Tracks/templates/TracksApp/project.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Projects</title>
	<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="js/bootstrap.js" ></script>
	<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.css">
    
</head>
<body>
	<header id="header" class="navbar navbar-static-top bs-docs-nav" style="background-color:#0000CC" role="banner">
    	<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        	<div class="navbar-header">
            	<a href="../" class="navbar-brand" style="color:#000000">Tracks</a>
            </div>
        </nav>
    </header>
    <div id="main" class="container-fluid">
    	<div class="row">
    		<div class="text-center"> 
    			Welcome to Tracks! Tracks is designed to allow musical collaboration from across the globe!
    		</div>
         </div>
    </div>
</body>
</html>
<body>
</body>
</html>

Tracks (Development)/Tracks/templates/TracksApp/signup.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Sign Up</title>
{% load staticfiles %}
<link href={% static "bootstrap-3.1.1-dist/css/bootstrap.min.css" %} rel="stylesheet">

<!-- Custom styles for this template -->
<link href={% static "starter-template.css" %} rel="stylesheet">

<!-- Universal js functions -->
<script src={% static "sidebar.js" %} type="text/javascript"></script>
<script type="text/javascript">
	function json_request(page, dict, success, failure) {
		console.log(dict)
		$.ajax({
			type: 'POST',
			url: page,
			data: dict,
			contentType: "application/json",
			dataType: "json",
			success: success,
			error: failure
    	});
	}
	function createAccount() {
		json_request(window.location + "/user/create", {email:$("#email").val(), firstname:$("#firstname").val(),lastname:$("#lastname").val(), password:$("#password").val(),confirm:$("#confirm").val()}, function(data) {
			alert(JSON.stringify(data));}, function(err) { alert("An error was encountered. " + err);});
	}
</script>
</head>

<body>
	<div id="navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation"></div>
	<div class="container" style="width:50%">
	<form id="signin" class="form-horizontal" role="form">
    	<div class="form-group" >
        	<label for="firstname" class="col-sm-2 control-label">First Name:</label>
            <div class="col-sm-10">
            	<input id="firstname" type="text"  class="form-control" placeholder="First Name"/>
            </div>
        </div>
        <div class="form-group" >
        	<label for="lastname" class="col-sm-2 control-label">Last Name:</label>
            <div class="col-sm-10">
            	<input id="lastname" type="text" class="form-control" placeholder="Last Name"/>
            </div>
        </div>
        <div class="form-group" >
        	<label for="email" class="col-sm-2 control-label">Email Address:</label>
            <div class="col-sm-10">
            	<input id="email" type="email" class="form-control" placeholder="Email"/>
        	</div>
        </div>
        <div class="form-group" >
        	<label for="password" class="col-sm-2 control-label" >Password:</label>
            <div class="col-sm-10">
            	<input id="password" type="password" class="form-control" placeholder="Password" data-toggle="tooltip" data-placement="top" title="Password must be 154 characters or less and can only contain alphanumeric characters."/>
            </div>
        </div>
        <div class="form-group" >
        	<label for="confirm" class="col-sm-2 control-label">Confirm Password:</label>
            <div class="col-sm-10">
            	<input id="confirm" type="password" class="form-control" placeholder="Confirm Password"/>
            </div>
        </div>
        <div class="col-sm-offset-2" style="padding-left:5px">
        	<button type="" class="btn btn-default" onSubmit="createAccount();" >Create Account</button>
        </div>
    </form>
    </div>
	{% load staticfiles %}
    <script src={% static "bootstrap-3.1.1-dist/js/bootstrap.min.js" %}></script>
    <script type="text/javascript">
		addNav();
	</script>
</body>
</html>

Tracks (Development)/Tracks/templates/TracksApp/tracks.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Tracks</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href={% static "bootstrap-3.1.1-dist/css/bootstrap.min.css" %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static "starter-template.css" %} rel="stylesheet">
    
    <!-- Universal js functions -->
    <script src={% static "sidebar.js" %} type="text/javascript"></script>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div id="navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation"></div>
    <div class="container">

      <div class="starter-template">
        <h1>Tracks 1.1</h1>
        <p class="lead">This is a bootstrap testing ground.<br> It looks pretty.</p>
      </div>

    </div><!-- /.container -->
	

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    {% load staticfiles %}
    <script src={% static "bootstrap-3.1.1-dist/js/bootstrap.min.js" %}></script>
    
    <script type="text/javascript">
		addNav();
	</script>
  </body>
</html>

Tracks (Development)/Tracks/templates/TracksApp/welcome.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>Tracks</title>

    <!-- Bootstrap core CSS -->
    {% load staticfiles %}
    <link href={% static "bootstrap-3.1.1-dist/css/bootstrap.min.css" %} rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href={% static "starter-template.css" %} rel="stylesheet">
    
    <!-- Universal js functions -->
    <script src={% static "sidebar.js" %} type="text/javascript"></script>>

    <!-- Just for debugging purposes. Don't actually copy this line! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
	<div id="navbar" class="navbar navbar-inverse navbar-fixed-top" role="navigation"></div>
    <div class="container" style="width:40%">

      <div class="starter-template">
        <h1>Welcome to Tracks</h1>
        <p class="lead">New? <a href="sign-up.html">Create an account</a>.</p>

        <form class="form-horizontal" role="form">
          <div class="form-group">
            <label for="inputEmail" class="col-sm-2 control-label">Email</label>
            <div class="col-sm-10">
              <input id="email" type="text" class="form-control" placeholder="Email">
            </div>
          </div>
          <div class="form-group">
            <label for="inputPassword" class="col-sm-2 control-label">Password</label>
            <div class="col-sm-10">
              <input id="password" type="password" class="form-control" placeholder="Password">
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-2 col-sm-3">
              <div class="checkbox">
                <label>
                  <input type="checkbox"> Remember me
                </label>
              </div>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-10">
              <button type="submit" class="btn btn-default" onClick="signIn()">Sign in</button>
            </div>
          </div>
        </form>
      </div>

    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    {% load staticfiles %}
    <script src={% static "bootstrap-3.1.1-dist/js/bootstrap.min.js" %}></script>
    <script type="text/javascript">
		addNav();
	</script>
    <script type="text/javascript">
    function json_request(page, dict, success, failure) {
      $.ajax({
        type: 'POST',
        url: page,
        data: JSON.stringify(dict),
        contentType: "application/json",
        dataType: "json",
        success: success,
        failure: failure
      });
    }

    function signIn() {
      dict = {email:$("#email").val(), password:$("#password").val()};
      console.log(dict);
      json_request(window.location + "/user/signIn", dict, function(data){console.log("data:" + data)}, function(err){alert("error")});
    }
    
    </script>
  </body>
</html>

Tracks (Development)/Tracks/templates/TracksApp/welcomepage.html
<!DOCTYPE html>
<html>
<head>
	<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
	<script src="js/bootstrap.js" ></script>
	<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="css/bootstrap-theme.css">
    
</head>
<body>
	<header id="header" class="navbar navbar-static-top bs-docs-nav" style="background-color:#0000CC" role="banner">
    	<nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
        	<div class="navbar-header">
            	<a href="../" class="navbar-brand" style="color:#000000">Tracks</a>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
    	<div class="row">
    		<div id="main" class="text-center"> 
    			Welcome to Tracks! Tracks is designed to allow musical collaboration from across the globe!
    		</div>
         </div>
    </div>
</body>
</html>